# 33
raide-project/ctf_public pull request #35
Opened 2019-05-23 01:53 UTC by shamith2

2019-05-24 16:58 UTC, skim0119 commented
Pull the Released branch and resolve conflicts

2019-05-24 16:59 UTC, skim0119 commented on cap_eval.py
> +        #print("blue team mean score: %.2f, std.dev. = %.2f" %(np.mean(blue_score), np.std(blue_score))
Remove the line

2019-05-24 20:37 UTC, skim0119 commented
Look into tqdm to put progress bar for large number of episode run.

2019-05-25 00:24 UTC, shamith2 commented on cap_eval.py
> +        #print("blue team mean score: %.2f, std.dev. = %.2f" %(np.mean(blue_score), np.std(blue_score))
Removed comments

2019-05-25 00:49 UTC, shamith2 commented
> Look into tqdm to put progress bar for large number of episode run.
added tqdm progress bar for episodes

2019-05-26 18:29 UTC, skim0119 requested changes
Could you append on README.md brief explanation of how to use this script?
>>> I updated README.md to include policy evaluation

2019-05-29 07:12 UTC, skim0119 approved these changes
cap_eval.py test finished

2019-05-29 07:14 UTC, merged